### ISSUE TITLE
作者友链怎么配置呢？

### ISSUE THREAD

**Issue by Konghuaiqing** [ChrAlpha/hexo-theme-cards#1]

**Comment by Konghuaiqing** [comment]
可以留个联系方式吗？

**Comment by ChrAlpha** [comment]
你好，可以参考文档：https://theme-cards.ichr.me/pages/#%E5%8F%8B%E6%83%85%E9%93%BE%E6%8E%A5

由于文档还有一点没未施工完成，所以暂时没有发布。

**Comment by ChrAlpha** [comment]
拜访了下您的博客，发现有部分主题修复过的 bug 仍在其中。

由于 Theme Cards 仍在开发初期，迭代较快，还请尽可能跟进最新版本。

**Comment by Konghuaiqing** [comment]
嗯嗯，知道了，谢谢。
