### ISSUE TITLE
关于highlight的配置

### ISSUE THREAD

**Issue by imoegirl** [ChrAlpha/hexo-theme-cards#100]
你好，文档中关于代码高亮部分的说明，有点混乱，配置了后不生效，不知道哪里出了问题，能不能给一个完整的配置。下面是我的配置，未生效

<img width="737" alt="截屏2021-07-25 下午10 06 03" src="https://user-images.githubusercontent.com/57443542/126902017-c827a784-71e1-4578-a2c5-4fc84b6ebc44.png">

**Comment by ChrAlpha** [comment]
把亮色、暗色代码高亮主题切换放进 [`darkmode.js`](https://github.com/ChrAlpha/hexo-theme-cards/blob/945b7a4b591d9360e99a3357f2bb46a4904b48c1/source/js/darkmode.js#L46) 里面了，导致没有开启深色模式的用户无法初始化代码高亮样式。

正在修复，感谢指出。

**Comment by ChrAlpha** [comment]
已在 [`60e9df4`](https://github.com/ChrAlpha/hexo-theme-cards/commit/60e9df4e2401ccfced1997d3196dbf5277d381e7) 尝试修复，请更新至最新 `canary` 分钟尝试。

如已修复抑或还有其它问题，请尽管在此贴回复。
