### ISSUE TITLE
在首页中，如果文章<!-- more -->前面的内容有图片的显示，则图片会显示不出来

### ISSUE THREAD

**Issue by imoegirl** [ChrAlpha/hexo-theme-cards#103]
post_asset_folder 设置为 true，图片放在对应文章的资源目录下。

在首页中，如果文章前面的内容有图片的显示，则图片会显示不出来。而在文章页面，显示是没有问题的。

![image](https://user-images.githubusercontent.com/57443542/130356996-f9d0bb97-43ab-4034-87d0-da04245288ec.png)

![image](https://user-images.githubusercontent.com/57443542/130357003-5890df40-137b-4c22-9540-5d24fe428331.png)

**Comment by ChrAlpha** [comment]
会使用资源文件夹的想必已经看过 Hexo 的文档，文档中就对这个问题有过 [解释](https://hexo.io/zh-cn/docs/asset-folders#%E7%9B%B8%E5%AF%B9%E8%B7%AF%E5%BE%84%E5%BC%95%E7%94%A8%E7%9A%84%E6%A0%87%E7%AD%BE%E6%8F%92%E4%BB%B6)。

> 通过常规的 markdown 语法和相对路径来引用图片和其它资源可能会导致它们在存档页或者主页上显示不正确。

> 如果通过使用相对路径的常规 markdown 语法 `![](example.jpg)` ，它将 *不会* 出现在首页上。（但是它会在文章中按你期待的方式工作）
>
> 正确的引用图片方式是使用下列的标签插件而不是 markdown ：
>
> ```
> {% asset_img example.jpg This is an example image %}
> ```
>
> 通过这种方式，图片将会同时出现在文章和主页以及归档页中。

希望能够仔细阅读文档。

**Comment by imoegirl** [comment]
感谢指点
