### ISSUE TITLE
zh-CN.yml 和 zh-TW.yml 参数有误

### ISSUE THREAD

**Issue by guangwenzhu** [ChrAlpha/hexo-theme-cards#105]
在 default.yml 中，设置成上述两种语言，导航仍然显示英文，不显示中文。
经排查，发现 post 和 page 里的两组参数位置写反了，交换后重新部署即可恢复。

![图片](https://user-images.githubusercontent.com/38041338/145349367-75478162-4c19-4e8d-a5d4-bce700996cd3.png)
![图片](https://user-images.githubusercontent.com/38041338/145349425-d717790a-c2a7-4f5c-ba60-7cacc5ba951d.png)

**Comment by ChrAlpha** [comment]
已在 `canary` 分支最新提交（[`f92816b`](https://github.com/ChrAlpha/hexo-theme-cards/commit/f92816bcd213eaccdd2fd6da1a5f50e78dee7639)）尝试修复，烦请测试。
