### ISSUE TITLE
表格不居中

### ISSUE THREAD

**Issue by Syize** [ChrAlpha/hexo-theme-cards#108]
生成的表格是靠左对齐的，在表格较宽时表现不明显，但表格较窄时非常影响美观

**Comment by ChrAlpha** [comment]
没明白。

是说整个表格左对齐不美观，还是说表格内容左对齐不美观？

markdown 样式是照搬 GitHub 的。

**Comment by Syize** [comment]
整个表格左对齐不美观，个人认为改成整个表格居中更好一点？

如图，如果表格内一行的内容较短时，整个表格的观感就会非常偏左
![image](https://user-images.githubusercontent.com/44666294/150888135-c56592f0-b8f2-4b71-99ad-53ae9742702a.png)
