### ISSUE TITLE
希望在友链页添加申请区和注意事项

### ISSUE THREAD

**Issue by Konghuaiqing** [ChrAlpha/hexo-theme-cards#11]
目前友链页面没有申请入口与友链说明，望添加，谢谢

**Comment by ChrAlpha** [comment]
不打算添加，不希望 Demo LInks 处沦为无脑推广蹭流量的地方，有缘人自取。就算提交 PR 也会先对站点做初步的判断，不保证照单全收。

**Comment by Konghuaiqing** [comment]
嗯嗯，知道了
