### ISSUE TITLE
颜色设置似乎有 bug

### ISSUE THREAD

**Issue by shadowquark** [ChrAlpha/hexo-theme-cards#110]
我在 themes/cards/_config.yml 里面改了黑白模式的颜色
```
color:
    main_color = "#000000"
    main_color_dark = "#FFFFFF"
```
hexo s 的时候，标题栏的颜色已经变成了黑白，没有问题。但是 hexo d 以后，又变回了默认的紫色，也就是 #6200ee。

这是一个 bug，还是我哪里没设置对呢。
感谢。

**Comment by ChrAlpha** [comment]
yaml 文件的赋值用冒号而非等号。

```jaml
style: 
  # 颜色配置
  color: 
    main_color: '#000000'
    main_color_dark: '#FFFFFF'
```

**Comment by shadowquark** [comment]
> yaml 文件的赋值用冒号而非等号。
> 
> ```
> style: 
>   # 颜色配置
>   color: 
>     main_color: '#000000'
>     main_color_dark: '#FFFFFF'
> ```

抱歉，我发帖的时候不小心打错了。。。我的 yaml 里面就是冒号。。。否则会报错的。。。
我是 hexo s 的时候已经设置成功了。但是 hexo d 的时候，还是最开始的紫色。

**Comment by shadowquark** [comment]
然后，我试图找了一下，有没有其它地方还有这个紫色的颜色信息。顺便把 `source/css/style/_base/_defines.styl` 里面的 `color_main` 和 `color_dark` 也改了。还是没用。。。`hexo s` 已经是黑色了，`hexo d` 以后还是紫色。

https://shadowquark.github.io/yyFish/
我非常困惑。

**Comment by ChrAlpha** [comment]
0. 尽量采用隐身模式调试，清除浏览器缓存。
1. `hexo s` 之前先尝试 `hexo cl`/`hexo clean`，清除 Hexo 缓存。
2. 在样式不符的页面中，打开开发者选项，检查 `<head>` 标签中的 CSS 资源标签是否是本地地址。若否，那么就是开启了 CDN，在主题配置文件中 `vendors.style` 中注释掉。参考 [主题文档](https://theme-cards.ichr.me/expert/#CDN)。

CSS 资源标签大概如下形式：

```html
<link rel="stylesheet" href="/css/style/main.css">
```

**Comment by shadowquark** [comment]
按你说的解决了。感谢耐心解答。祝主题越来越好。
