### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by hmsjy2017** [ChrAlpha/hexo-theme-cards#111]
1. 友链支持加入简介，并随机排序
类似这样：
![D96F8E97-B6D9-48AA-80E3-DCFC30DF257A](https://user-images.githubusercontent.com/42692274/152171785-e762a5fe-cceb-4c88-be6c-deb364248411.jpeg)
2. 卡片式版权声明，并加入 CC 图标
类似这样：
![9AA9FD62-BA50-4301-ACAF-E5EB8B48BEBC](https://user-images.githubusercontent.com/42692274/152172015-15a17b03-6ef4-4d39-84b3-7c1071b7b0e6.jpeg)
3. 顶栏半透明
类似这样：
![5AAFAA6F-A010-4678-811F-D6B575BDC177](https://user-images.githubusercontent.com/42692274/152172885-5e1ca558-33f4-4083-9f7b-6af8ba37001e.jpeg)
4. 右侧加入目录图标，点击展开，文章居中展示。
类似这样：
![B1E51BED-43B3-48FA-B34E-7316B471D054](https://user-images.githubusercontent.com/42692274/152173952-82e9d415-7710-491c-9293-726f2d76a4da.jpeg)
另外，现在目录容易挡住文字。
![839D4E6D-EB15-4361-BC48-3A956C7EFF32](https://user-images.githubusercontent.com/42692274/152174381-501e375a-446a-495f-837b-ff3cc1a383f9.jpeg)
5. 文章底部加入赞赏按钮。
类似这样：
![8E315547-DCF3-42B4-B9D9-017186809BE5](https://user-images.githubusercontent.com/42692274/152174197-6743398e-8c8b-4f7f-9ed3-6a4ac6efa865.jpeg)

**Comment by ChrAlpha** [comment]
1. 友链随机排序需要引入额外 JavaScript，没有此打算。另外，Cards 早已支持友链简介，`link.desc` 进行一段描述或 `link.tags` 添加几个标签都是可以正常识别并展示的。
2. 我博客中的卡片式版权声明是照搬另一个开源主题的，不方便直接加入。
3. 顶部栏有背景毛玻璃效果（blur），类似半透明且层次性更强，在没有明显边界（我博客的导航栏额外加了边界线的）的情况下可读性更好。
4. 仅有当显示宽度较小时——比如在移动端上——才会收起目录并要求手动调出，一般情况下目录直接在一侧效率更高。挡文字是底部组件没有对齐的 Bug，现已尝试修复（[`1ee2529`](https://github.com/ChrAlpha/hexo-theme-cards/commit/1ee25296492d6e70316d720fc97e824ea06ff8bb)）。
5. 目前尚且没有一致承认的捐赠平台，「添加涉及金钱交易的组件」的这种行为本身就带有我个人的倾向在其中，不够中立，私以为不妥。待真正公认的捐赠平台出现前暂时不会有此计划。
