### ISSUE TITLE
iOS Safari Compatibility Problem

### ISSUE THREAD

**Issue by Alendia** [ChrAlpha/hexo-theme-cards#115]
For a browser whose core is WebKit, text-size-adjust may result in text auto adjust with some strange behaviour.

https://github.com/ChrAlpha/hexo-theme-cards/blob/88ede96fedc3647f723381931173d69533d341df/source/css/style/_base/markdown.styl#L359-L363

This snippet will result in such a situation below.
![image](https://user-images.githubusercontent.com/44888915/161436590-4b892f03-7d16-4cd6-b497-d3ebf04bdcab.png)

**Comment by ChrAlpha** [comment]
sorry that I'm too busy these months to solve this issue and delay it till now.

Good news is I'm now working with it.
Bad news is I have to clarify that theme Cards has no plan to support IE and other old browsers any longer, which means I'll only try to solve the problem on Firefox and Safari.

![image](https://user-images.githubusercontent.com/53332481/175864694-514b9ba3-5857-469e-93b3-751b1ed9690d.png)

**Comment by ChrAlpha** [comment]
Well, it's so strange that I can't reappear it on iOS Safari 15.4 or Firefox. So I don't think `text-size-adjust` matters for this issue. Could you please share more info?

![image](https://user-images.githubusercontent.com/53332481/176671745-16af2d4e-040f-4c9f-bd57-61bba3384337.png)

**Comment by Alendia** [comment]
Actually I changed your code locally, so my blog performs normally. I can pull request if you don’t mind.

**Comment by ChrAlpha** [comment]
So I just remove those useless 4 lines and...take a look at [`dd8b9bc`](https://github.com/ChrAlpha/hexo-theme-cards/commit/dd8b9bcb1c85b4be1ae8fa54735dd93dd9b2b828)?
