### ISSUE TITLE
Vendor中的示例note css不存在？

### ISSUE THREAD

**Issue by Moraxyc** [ChrAlpha/hexo-theme-cards#125]
_config.yml中的note vendor示例地址为[note.min.css](https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.4/dist/css/style/note.min.css)，然而该css并不存在，页面中note是main.min.css渲染的

**Comment by ChrAlpha** [comment]
是的，样式已经直接引入到 `main.css` 中的
