### ISSUE TITLE
移动端文章目录展开后无法收起

### ISSUE THREAD

**Issue by Arictia** [ChrAlpha/hexo-theme-cards#126]
如题，使用的是Safari，点击页面其他位置也无法收起或关闭，源码中好像没有找到在哪里可以设置的样子

**Comment by ChrAlpha** [comment]
我在移动端测试了 [Demo](https://theme-cards.ichr.me/demo/2018/07/markdown/)，点击空白位置即可收起目录，浏览器为 Safari 16.4.1
