### ISSUE TITLE
主题色修改不生效

### ISSUE THREAD

**Issue by hmsjy2017** [ChrAlpha/hexo-theme-cards#128]
修改为橙色时，仍显示紫色主题。
![Screenshot_2023-09-22-10-30-30-292_com android chrome-edit](https://github.com/ChrAlpha/hexo-theme-cards/assets/42692274/054e2429-aacf-4fd0-98e4-d923505f524a)
![Screenshot_2023-09-22-10-31-18-500_com android chrome-edit](https://github.com/ChrAlpha/hexo-theme-cards/assets/42692274/e56264d8-8a4f-4d5f-abfe-569af1cf2672)

**Comment by ChrAlpha** [comment]
看看 `vendors.style` 有没有留空

**Comment by hmsjy2017** [comment]
感谢指导

**Comment by hmsjy2017** [comment]
不过我发现对 `dark.min.css` 使用 CDN 也会导致主题色修改不生效。
![image](https://github.com/ChrAlpha/hexo-theme-cards/assets/42692274/364e5603-cb3b-4084-9f3d-57dadab5f515)

**Comment by ChrAlpha** [comment]
> 不过我发现对 `dark.min.css` 使用 CDN 也会导致主题色修改不生效。 ![image](https://private-user-images.githubusercontent.com/42692274/274878844-364e5603-cb3b-4084-9f3d-57dadab5f515.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDk0MzgsIm5iZiI6MTcwMTkwOTEzOCwicGF0aCI6Ii80MjY5MjI3NC8yNzQ4Nzg4NDQtMzY0ZTU2MDMtY2IzYi00MDg0LTlmM2QtNTdkYWRhYjVmNTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAwMzIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NzcyNmE3ZDNlNzkzZGU0ZTRjODNmYzYxODdhZTBlMjM5ZDRkMzA5YmY5MTg2YTQxOWU3MzM1OGQ5NjJiNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Foyh0LXy2uP0firLaZLyJFJgZgt8SBMpBNg-ep0HLjA)

感谢提醒，后续我会更新文档说明
