### ISSUE TITLE
代码块没有背景

### ISSUE THREAD

**Issue by kun2256** [ChrAlpha/hexo-theme-cards#129]
<img width="524" alt="截屏2024-06-09 12 00 27" src="https://github.com/ChrAlpha/hexo-theme-cards/assets/93712124/20629404-049a-43a4-a3e1-7385bce4862a">

**Comment by ChrAlpha** [comment]
[Theme Cards Demo - Code Highlight Style test](https://theme-cards.ichr.me/demo/2019/07/code-highlight/) 中的代码块样式正常，能否提供更多信息──例如配置文件？

**Comment by ChrAlpha** [comment]
访问您的网站发现代码块渲染正常，暂时关闭此 issue，若仍有问题随时提起。
