### ISSUE TITLE
languages问题

### ISSUE THREAD

**Issue by Konghuaiqing** [ChrAlpha/hexo-theme-cards#13]
如图：
![image](https://user-images.githubusercontent.com/58429614/80946850-8d112f00-8e21-11ea-9c9b-94a4892984ef.png)
zh-CN中的footer部分与en相同，建议更改
![image](https://user-images.githubusercontent.com/58429614/80947108-0741b380-8e22-11ea-97bb-0713b83edab4.png)
 这里的协议地址也不对，写成了en

**Comment by ChrAlpha** [comment]
后续会重写language库，其实还有许多条目并未在主题任何地方调用。
