### ISSUE TITLE
Gitalk 422 Valid failed

### ISSUE THREAD

**Issue by Wizardgreen** [ChrAlpha/hexo-theme-cards#132]
> **您好，我是來自台灣並慣用繁體中文的開發者，**
> **本 Issue 的目的是在於發現問題並協力改善，**
> **如果有任何語意造成不適，先在這說聲不好意思。**

### Issue：
使用 Gitalk 在創建 issue 時遭遇到 error code 422。

<img width="676" alt="Screenshot 2024-07-29 at 12 55 33 PM" src="https://github.com/user-attachments/assets/077bb408-0dd2-4439-99b0-292db5115a1c">

### Root cause：
**路徑：**
 .../cards/layout/_plugins/comments/gitalk/source.ejs
 
**行數：**
14

**問題：**
gitalk.id 寫死為 window.location.pathname，這雖然是原作者的預設值，
但是長度過長會導致無法創建用來識別 comment 的 issue label id。

### Action：
我正在修，晚點會發 PR。

### Ref：
https://blog.csdn.net/Keith_Prime/article/details/111604291

**Comment by ChrAlpha** [comment]
特殊字符的 URL 编码确实会导致 pathname 过长，感谢提醒。

**Comment by Wizardgreen** [comment]
@ChrAlpha 請問這個更新有預計在什麼時候上線嗎?
