### ISSUE TITLE
更新主题后valine无法使用

### ISSUE THREAD

**Issue by Konghuaiqing** [ChrAlpha/hexo-theme-cards#14]
如下图：
![image](https://user-images.githubusercontent.com/58429614/81549791-e1805580-93b1-11ea-9ed6-3b659903804e.png)
![image](https://user-images.githubusercontent.com/58429614/81549821-e8a76380-93b1-11ea-9a57-f7e6174f5a72.png)
经过推测，发现了一个bug，如下图：
![image](https://user-images.githubusercontent.com/58429614/81549969-299f7800-93b2-11ea-870f-05088dd72425.png)
在这里加入了一个defer，貌似加入后就无法加载评论了
我尝试去掉“defer”，经测试，成功使用。

**Comment by ChrAlpha** [comment]
当初给非关键资源无脑异步留下的问题。

初始化时资源并未加载完全，导致如是报错。

已在 [`ef71a29`](https://github.com/ChrAlpha/hexo-theme-cards/commit/ef71a297801fdd91381c4be77fd6c2b841f50c6d) 尝试修复，请获取最新 master 分支。

**Comment by Konghuaiqing** [comment]
你好，经过测试，在最新版本中已成功正常使用
---
另外，valine缺少了一个配置项，如下
![image](https://user-images.githubusercontent.com/58429614/82107744-9de46d80-975c-11ea-82a7-aa3486c288c7.png)

**Comment by ChrAlpha** [comment]
已在 [`cb13e4f`](https://github.com/ChrAlpha/hexo-theme-cards/commit/cb13e4f616fce42bad5d114da7cb1d1ec865c101) 中尝试支持，请测试最新 master 分支。

另外 valine 更新频繁，下一个测试版本（`0.3`）可能会直接采用配置文件 stringify 的方案，届时只需在 `_config.yml` 中添加相应配置项即可，无需再修改模板。

**Comment by Konghuaiqing** [comment]
另外，更新主题后，貌似只有文章能进行评论
其他的pages开启了commet为true无作用
貌似没加载

**Comment by ChrAlpha** [comment]
> 另外，更新主题后，貌似只有文章能进行评论
> 其他的pages开启了commet为true无作用
> 貌似没加载

页面评论开启强制开启参数名为 `comments`，并非 `comment`，更不是 `commet`（都拼写错误了…）。

从代码角度来看开启逻辑是没有问题的，我在本地 demo 测试也是可以的。

**Comment by Konghuaiqing** [comment]
我这边还是不行呢

**Comment by ChrAlpha** [comment]
> 我这边还是不行呢

拉取最新 master 分支再尝试下？

**Comment by Konghuaiqing** [comment]
好的

**Comment by Konghuaiqing** [comment]
感谢，最新master分支pull后成功
