### ISSUE TITLE
文章目录显示错误

### ISSUE THREAD

**Issue by Konghuaiqing** [ChrAlpha/hexo-theme-cards#16]
>我使用的主题：最新的master分支。

如图：
![image](https://user-images.githubusercontent.com/58429614/82754266-66ca2800-9dfe-11ea-8c5f-934ad0f29fd7.png)
不知道为什么，在过多目录的文章中，会出现显示错误的bug，望修复，谢谢！

**Comment by longlivewe** [comment]
我也遇到了一样的问题，这个功能让我关上了

**Comment by Konghuaiqing** [comment]
再次报告bug：
开启目录显示后手机端访问体验不佳，如图
![image](https://user-images.githubusercontent.com/58429614/83027691-fec84b80-a062-11ea-9942-a4a2af0f3410.png)
望修复，谢谢
另外，貌似旧文章提醒失效了，不起作用

**Comment by ChrAlpha** [comment]
很奇怪，你所说的两个问题我都没能复现。请尝试强制获取最新 master 分支，即重新 git clone 仓库。
如能提供部分源码供我 debug 将更好了。

**Comment by Konghuaiqing** [comment]
貌似是因为带有数字呢，如：
1.xxxx
2.xxxxx
难道说与那个添加数字序号的选项冲突？
目前另一个文章没有出现错误
![image](https://user-images.githubusercontent.com/58429614/83140214-4b259100-a120-11ea-913a-f5a8675a0723.png)
 另外，我已经更新到最新的master分支，暂未解决

**Comment by Konghuaiqing** [comment]
难道说是文章的问题？
![image](https://user-images.githubusercontent.com/58429614/83140398-99d32b00-a120-11ea-831e-42e41fec5c5b.png)
![image](https://user-images.githubusercontent.com/58429614/83140413-9fc90c00-a120-11ea-8ff8-11e751a1136f.png)

**Comment by longlivewe** [comment]
这个有好多人反映了，关上目录功能吧，估计下个版本能解决。

**Comment by ChrAlpha** [comment]
请按照顺序添加标题，从二级标题开始。

不要出现：

```
## 二级标题

#### 四级标题

### 三级标题
```

等违背 markdown 排版规范的标题声明。

另外**不要再声明一级标题**，我也在文档中说明了理由。

我自己博客中无论是序号还是移动端都正常显示，如有仍疑问麻烦提供文章 markdown 源码，不胜感激！

**Comment by ChrAlpha** [comment]
请确保全文第一个标题声明层级最高，不要出现后续标题层级有比第一个标题高的情况：

```
### 三级标题

## 二级标题

### 三级标题

#### 四级标题
```

也不要出现跨越声明：

```
## 二级标题

#### 四级标题
```

**Comment by Konghuaiqing** [comment]
好的，文章已经调整成你说的样式，修复了
但我觉得，一般新手不会太了解Markdown规范吧
