### ISSUE TITLE
构建成功后控制台报错：Uncaught TypeError: Cannot read property 'src' of null

### ISSUE THREAD

**Issue by plusmultiply0** [ChrAlpha/hexo-theme-cards#17]
我是根据[这个](https://theme-cards.ichr.me/start/)进行操作的，此外没干什么。
本地生成静态文件后hexo g--debug页面生成正常。
如图：![error2.png](https://i.loli.net/2020/06/02/kYJm3oVPW1e8nQq.png)
上传到远程仓库后，成功构建后，进入博客页面白屏，打开控制台发现错误：
Uncaught TypeError: Cannot read property 'src' of null。
如图：![error.png](https://i.loli.net/2020/06/02/YPHDGgzMWK79xsq.png)
bug.log也没发现什么问题，博客在安装theme前也能正常访问。
不知道是什么问题，请指教

**Comment by Konghuaiqing** [comment]
可以提供你的博客_config吗

**Comment by Konghuaiqing** [comment]
或者试试hexo s -debug

**Comment by plusmultiply0** [comment]
博客config可以去我的GitHub上看，[这里](https://github.com/plusmultiply0/plusmultiply0.github.io/tree/hexo)
hexo s --debug如图：
![error3.png](https://i.loli.net/2020/06/02/vWdaLCVnzi9lT1G.png)

**Comment by Konghuaiqing** [comment]
等会？Github可以构建？
![image](https://user-images.githubusercontent.com/58429614/83514839-f52d6080-a506-11ea-88ac-7b934fa2e933.png)
而且主题也不在仓库，如果可以构建，要将cards`git子项目管理`

**Comment by Konghuaiqing** [comment]
等会？Github可以构建？
![image](https://user-images.githubusercontent.com/58429614/83514839-f52d6080-a506-11ea-88ac-7b934fa2e933.png)
而且主题也不在仓库，如果可以构建，要将cards`git子项目管理`

**Comment by plusmultiply0** [comment]
@Konghuaiqing 
问题解决了，谢谢！
