### ISSUE TITLE
暗色模式下的disqus文字显示错误

### ISSUE THREAD

**Issue by Konghuaiqing** [ChrAlpha/hexo-theme-cards#18]
如图：
![image](https://user-images.githubusercontent.com/58429614/83522415-375c9f00-a513-11ea-8a74-d6ca85e6690d.png)
![image](https://user-images.githubusercontent.com/58429614/83522418-37f53580-a513-11ea-90b1-a90cf1b87f91.png)

**Comment by ChrAlpha** [comment]
DisqusJS 没有适配暗色模式，这个不是很好解。
但是 Disqus 本身是可以通过调整样式为 _auto_ 来解决这个

**Comment by Konghuaiqing** [comment]
暗黑模式的表格？
![image](https://user-images.githubusercontent.com/58429614/83936216-1f776a80-a7f4-11ea-8476-05de910600a6.png)

**Comment by ChrAlpha** [comment]
> 暗黑模式的表格？
> ![image](https://user-images.githubusercontent.com/58429614/83936216-1f776a80-a7f4-11ea-8476-05de910600a6.png)

已在 Cards@0.3.4 中尝试修复，请将 Vendors 切换为：

```yaml
style: https://cdn.jsdelivr.net/npm/hexo-theme-cards@0.3.4/dist/css/style.min.css
highlight: https://cdn.jsdelivr.net/npm/hexo-theme-cards@0.3.4/dist/css/github.min.css
```

强制获取最新版。
