### ISSUE TITLE
主题如何使用自定义字体文件？

### ISSUE THREAD

**Issue by plusmultiply0** [ChrAlpha/hexo-theme-cards#19]
如题，
1. 是在markdown.styl文件（path: themes/cards/layout/source/css/markdown.styl）里改吗？
（尝试加了几个字体，貌似没用）

2. 引入的字体文件放在哪里？

希望能给个说明，谢谢！

**Comment by ChrAlpha** [comment]
主题是允许从外部引入字体文件的，无论是 Stylus 还是 CSS 格式都能被识别并正常转换。你所谓的「没用」大概率是引入了字体文件但是没有引用。

打个比方：

```stylus
// theme/source/style.styl

@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC&display=swap');

p
h2
h3
h4
h5
h6
    font-family 'Noto Sans SC'!important
```

当然，你也可以给全局引用该字体：

```stylus
// theme/source/style.styl

@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC&display=swap');

*
    font-family 'Noto Sans SC'!important
```

根据规定，请确保 `@import` 在开头，并且后续应用时加上 `!important` 参数防止被覆盖。
