### ISSUE TITLE
darkmode 问题

### ISSUE THREAD

**Issue by Royce003** [ChrAlpha/hexo-theme-cards#20]
https://cdn.jsdelivr.net/npm/hexo-theme-cards@0.5/dist/js/darkmode.min.js

最新版 darkmode.js 会报错，但主题里的那个不会
例如：https://theme-cards.ichr.me/demo/  , demo 用的 0.4 版本（0.4 和 0.5 代码应该完全一样）

**Comment by ChrAlpha** [comment]
我在本地单元测试，无论是调用 v0.4 还是 v0.5 的 `darkmode.js`，都没能复现问题。
拜访了下您的站点，似乎对主题进行了深度定制（比如 note 标签），如果可以的话方便公开部分源代码以供调试吗？

**Comment by Royce003** [comment]
这是博客公开仓库 https://github.com/royce003/simpleHexo ，note 标签的 css 也是新增了一个文件，在 https://github.com/royce003/simpleHexo/blob/master/themes/cards/source/css/tag_plugin.styl ，其他的基本未修改。

然后，报错是在 [demo](https://theme-cards.ichr.me/demo/) 中发生的，我这试了多个浏览器，都是报错。
![image](https://user-images.githubusercontent.com/57910033/85147770-e6bea300-b281-11ea-8995-09128312f4c2.png)

**Comment by ChrAlpha** [comment]
明白了，`dist/js/` 中的文件没有和 `source/js/` 中的 `darkmode.js` 同步，之前修复 onload bug 的时候没有更新资源文件夹。

现已更新，部分地区由于 CDN 缘故可能会有不同程度的滞后。

**Comment by Royce003** [comment]
嗯嗯。
