### ISSUE TITLE
主颜色配置无效

### ISSUE THREAD

**Issue by Konghuaiqing** [ChrAlpha/hexo-theme-cards#21]
系统：Windows10 2004
主题版本：在此次issues前的最新commit
问题如下
![image](https://user-images.githubusercontent.com/58429614/85690855-8eb2f100-b706-11ea-9976-6f2ebd082e82.png)
这是我的cards.yml中的样式配置，已设置主颜色
但本地预览测试时发现颜色没有发生变化，望解答

**Comment by ChrAlpha** [comment]
1. 请注释掉 `vendors.style`，或将其设置为 `css/style.css` 以关闭样式 CDN。
2. 由于数据文件特性，更新 `source/_data/` 内的文件全部需要重新 `hexo s` 或 `hexo g` 时才生效。

**Comment by Konghuaiqing** [comment]
已解决
