### ISSUE TITLE
MathJax 渲染失败

### ISSUE THREAD

**Issue by robinzyb** [ChrAlpha/hexo-theme-cards#22]
hello
  我的文章经常有很多公式，添加了frontmatter：MathJax: true之后渲染出了点问题，有部分公式被渲染，有部分没有同时有很大错位。我对网页技术不是很了解。请问可能是什么问题？

https://robinzyb.github.io/2020/05/24/hf_python/
5月23号git clone的版本还是没有问题的，渲染是正常的。

**Comment by ChrAlpha** [comment]
请检查是否更改过渲染器，单元测试中，Hexo 默认的 `hexo-renderer-marked` 是能正常渲染的。

另，刚刚拜访了您的网站，似乎还在使用老旧 `style.css` ，建议手动指定至 `v0.6` 以上版本或关闭 CDN，从而避免某些样式错误

**Comment by robinzyb** [comment]
好的，
我重新把card.yml修改了一下 把cdn关闭了。样式问题没有大碍了。谢谢！
我重新安装了一次hexo-rendere-marked，渲染有改变，但是不知道为什么有一块公式仍然没有渲染
https://robinzyb.github.io/2020/05/24/hf_python/
这块使用latex命令，用$$..$$来指示数学环境。其他数学环境都正确渲染了，仅有这块没有。

**Comment by ChrAlpha** [comment]
在未渲染的部分中途有一段被渲染成斜体，怀疑是与 markdown 语法冲突。请尝试重新编写，或者更换合适的渲染器。

**Comment by NeroAsmarr** [comment]
可以使用这个渲染器，不用去修改什么了https://blog.csdn.net/qq_36667170/article/details/105846999
