### ISSUE TITLE
关于评论懒加载

### ISSUE THREAD

**Issue by JalenChuh** [ChrAlpha/hexo-theme-cards#23]
请问现在评论懒加载是还没有推到 master 吗？看你博客有了，但是主题没看到相关配置。

**Comment by ChrAlpha** [comment]
暂时没有将此功能添加至主分支的打算，有兴趣的话可以参考我博客文章自行修改源代码（同时意味着放弃主题平滑更新）。

**Comment by JalenChuh** [comment]
谢谢
