### ISSUE TITLE
评论无法显示

### ISSUE THREAD

**Issue by koyangyang** [ChrAlpha/hexo-theme-cards#24]
comment: true
valine我也已经配置好了，就是文章不显示评论功能，只有文字Comments，没有任何输入框和按钮

**Comment by ChrAlpha** [comment]
猜测为空配置项带来的问题，已在 [`d62a31f`](https://github.com/ChrAlpha/hexo-theme-cards/commit/d62a31ffd6a2099b5b5dbbb59237ccef5fb3a04d) 尝试修复，请拉取最新 master 分支。

**Comment by koyangyang** [comment]
我在crads文件夹git pull后还是无法显示评论

**Comment by ChrAlpha** [comment]
本地测试是通过了的，请再次检查配置项。

![image](https://user-images.githubusercontent.com/53332481/86910224-ee1ff080-c14b-11ea-8cde-0377a32bee0b.png)

**Comment by koyangyang** [comment]
好的已经排查问题，有别的冲突了，现在已经解决，谢谢开发者
