### ISSUE TITLE
首页logo能加个圆框和阴影吗?

### ISSUE THREAD

**Issue by forliuyifei** [ChrAlpha/hexo-theme-cards#25]
![image](https://user-images.githubusercontent.com/53306807/86993518-c4f87200-c1d6-11ea-9be8-732953fa8aed.png)
经测试应该是72x72的图片尺寸最合适, 我不知道怎么在css里针对这个头像的img进行指定样式, 修改 .cover .cover_logo没反应。
有交流群吗请问？

**Comment by ChrAlpha** [comment]
建议直接裁图片，这里只限制了最大宽度。

**Comment by forliuyifei** [comment]
> 建议直接裁图片，这里只限制了最大宽度。

好的我明白了，之前没有取消固定样式，现在改成自定义成功了

**Comment by forliuyifei** [comment]
https://loafing.cn/
 查看效果
