### ISSUE TITLE
谷歌搜索引擎html文件验证网站所有权失败

### ISSUE THREAD

**Issue by forliuyifei** [ChrAlpha/hexo-theme-cards#26]
我把谷歌提供的html文件放在source文件夹下面，结果应该是hexo g的时候被渲染了样式，所以谷歌那边验证不通过。
打开https://loafing.cn/google892d03eefca55fd0.html
可以看见它并不是直接显示一串乱码。

**Comment by forliuyifei** [comment]
直接进GitHub仓库修改
![Screenshot_20200710-081331](https://user-images.githubusercontent.com/53306807/87102738-5e7e5d00-c285-11ea-94bc-88b461bae53a.png)

![Screenshot_20200710-081248](https://user-images.githubusercontent.com/53306807/87102752-6b9b4c00-c285-11ea-8398-455965a9e476.png)

验证成功，但下次又会失效🤔

**Comment by ChrAlpha** [comment]
这并不属于主题的问题，在 **站点配置文件** 中修改 `skip_render` 跳过指定页面的模板渲染。

```yaml
skip_render: 
  - google892d03eefca55fd0.html
```

详见 [Hexo 文档](https://hexo.io/zh-cn/docs/configuration#%E7%9B%AE%E5%BD%95)。

其实亦可通过 `<meta>` 标记证明所有权，这时只需要在 **主题配置文件** 中的「[head - custom_text](https://theme-cards.ichr.me/config/#custom-text)」加入相应配置即可，这种方法也是我们更提倡的。

**Comment by forliuyifei** [comment]
> 这并不属于主题的问题，在 **站点配置文件** 中修改 `skip_render` 跳过指定页面的模板渲染。
> 
> ```yaml
> skip_render: 
>   - google892d03eefca55fd0.html
> ```
> 
> 详见 [Hexo 文档](https://hexo.io/zh-cn/docs/configuration#%E7%9B%AE%E5%BD%95)。
> 
> 其实亦可通过 `<meta>` 标记证明所有权，这时只需要在 **主题配置文件** 中的「[head - custom_text](https://theme-cards.ichr.me/config/#custom-text)」加入相应配置即可，这种方法也是我们更提倡的。

好的, 学到了
