### ISSUE TITLE
移动端文章页能取消页边距吗？

### ISSUE THREAD

**Issue by forliuyifei** [ChrAlpha/hexo-theme-cards#27]
但首页的卡片样式还是保留一下比较好看。

现在文章页正文一行顶多21个汉字，换行过于频繁。
应该调整为显示25个汉字更适合阅读吧。

给个开关或者调整的选项？

**Comment by forliuyifei** [comment]
当然了，这是一个非常主观的想法，也许只是我的习惯问题😅

**Comment by forliuyifei** [comment]
另外，Copyright license框框在手机上看着也不太友好，链接一长，很容易就显示成5行，能紧凑一点控制在3行最好吧

**Comment by ChrAlpha** [comment]
完全取消页边距不见得非常合适，一定的边距能够营造边界感，防止一种内容溢出屏幕外的顾虑。

按照您的描述，就算完全取消边距也到不了 25 个汉字。

Lisence 太多行确实是个问题，后续需要更新下页边距，如果有推荐的数值欢迎告诉我们。

**Comment by forliuyifei** [comment]
> 完全取消页边距不见得非常合适，一定的边距能够营造边界感，防止一种内容溢出屏幕外的顾虑。
> 
> 按照您的描述，就算完全取消边距也到不了 25 个汉字。
> 
> License 太多行确实是个问题，后续需要更新下页边距，如果有推荐的数值欢迎告诉我们。

嗯，又习惯了几天，想要统一卡片风格的话，确实不应该取消文章页卡片边距。
License的字体暂时可以改成font-size small，比正文小一点没关系。
还有就是，author这个头部信息自定义无效，License还是显示默认的作者，希望有空优化一下。

**Comment by ChrAlpha** [comment]
> > 完全取消页边距不见得非常合适，一定的边距能够营造边界感，防止一种内容溢出屏幕外的顾虑。
> > 按照您的描述，就算完全取消边距也到不了 25 个汉字。
> > License 太多行确实是个问题，后续需要更新下页边距，如果有推荐的数值欢迎告诉我们。
> 
> 嗯，又习惯了几天，想要统一卡片风格的话，确实不应该取消文章页卡片边距。
> License的字体暂时可以改成font-size small，比正文小一点没关系。
> 还有就是，author这个头部信息自定义无效，License还是显示默认的作者，希望有空优化一下。

author 信息是在主题配置文件「meta - author - name」中获取的，本地测试可以自定义。
