### ISSUE TITLE
主题中间头像设置后没有约束框，大小会出现问题。

### ISSUE THREAD

**Issue by NeroAsmarr** [ChrAlpha/hexo-theme-cards#28]
![截屏2020-07-12上午1 03 14](https://user-images.githubusercontent.com/44702685/87229564-93042d00-c3db-11ea-9108-a8a043e52bf2.png)
情况如图

**Comment by JalenChuh** [comment]
css 中增加代码

```stylus
.cover__logo img
  border-radius 100%
  width 90px
  height 90px
```

顺便，为啥和我头像~~辣么像~~（一样）😆

**Comment by NeroAsmarr** [comment]
> css 中增加代码
> 
> ```stylus
> .cover__logo img
>   border-radius 100%
>   width 90px
>   height 90px
> ```
> 
> 顺便，为啥和我头像~辣么像~（一样）😆

感谢，！因为就是你的头像hhh，因为我开始用的png，然后我以为是webp才能这样效果，所以我给换了一下，还是这样才直接截图的。

**Comment by ChrAlpha** [comment]
最初支持封面添加 logo 的时候，本意是方便大家添加一个同时包含图标和名称的横幅，所以只限制最大宽度。

不过大家似乎都执着于头像，那就先类比上面的方法自行添加，后续我们再考虑是否直接并入主题中。

**Comment by NeroAsmarr** [comment]
> 最初支持封面添加 logo 的时候，本意是方便大家添加一个同时包含图标和名称的横幅，所以只限制最大宽度。
> 
> 不过大家似乎都执着于头像，那就先类比上面的方法自行添加，后续我们再考虑是否直接并入主题中。

辛苦辛苦，主题真的很漂亮，

**Comment by JalenChuh** [comment]
> > css 中增加代码
> > ```stylus
> > .cover__logo img
> >   border-radius 100%
> >   width 90px
> >   height 90px
> > ```
> > 
> > 
> > 顺便，为啥和我头像~辣么像~（一样）😆
> 
> 感谢，！因为就是你的头像hhh，因为我开始用的png，然后我以为是webp才能这样效果，所以我给换了一下，还是这样才直接截图的。

hhhhhh

**Comment by ChrAlpha** [comment]
已在 [`de238bb`](https://github.com/ChrAlpha/hexo-theme-cards/commit/de238bb9ef39eac27648f6f55853ef0c1c54393e) 尝试实现此 issue 描述的特性，由主题配置项 `cover.avatar` 控制。
