### ISSUE TITLE
再次请教大佬~，valine配置中的自定义表情怎么添加呀

### ISSUE THREAD

**Issue by Konghuaiqing** [ChrAlpha/hexo-theme-cards#3]
![image](https://user-images.githubusercontent.com/58429614/80475795-002b2900-897c-11ea-8c60-62fd66386e09.png)
我照着官网的格式添加了
hexo g的时候报错一大串呢
是因为配置有误？还是不支持？
望答复
PS：README.md中的“正在使用Cards主题的blog”可以添加我的嘛
网址：https://blog.ninglans.top/
名称：Kongerの万事屋

**Comment by ChrAlpha** [comment]
暂未支持添加表情的功能，报错是正常的，之后考虑更新。

配置文件中的 `app_id` 与 `app_keys` 直接在 `valine` 条目下，不需要 `leancloud`。 请对照最新的 [配置文件](https://github.com/ChrAlpha/hexo-theme-cards/blob/master/_config.yml) 

至于站点分享，会帮您加上的，但是形式形式暂时没有想好。

**Comment by Konghuaiqing** [comment]
嗯嗯，收到

**Comment by ChrAlpha** [comment]
在 [`7d1c6e7`](https://github.com/ChrAlpha/hexo-theme-cards/commit/7d1c6e7a02424197cfea0a89250aaf1b32d2039d) 中添加了支持，可以再次尝试。

由于我不使用 Valine，此次更新没有排查，只是按照 Valine 官方文档进行适配。所以如果此类功能带来的 bug，请重新打开此 issue 反馈。感谢！
