### ISSUE TITLE
多级目录显示效果不佳

### ISSUE THREAD

**Issue by DuranceX** [ChrAlpha/hexo-theme-cards#31]
文章页面中多级目录的显示效果好像不太好，感觉挺急的，而且也不太好区分😂

**Comment by DuranceX** [comment]
挺挤。。

**Comment by ChrAlpha** [comment]
目录限制最大宽度 220px，这个数值是从 [Hexo 官网](https://hexo.io) 主题参考得出。固定宽度是为了更好地适配响应式布局，如有更好的数值或者更好的实现方式也欢迎提出。
