### ISSUE TITLE
文章目录bug，点击无响应，不跳转至对应的位置

### ISSUE THREAD

**Issue by forliuyifei** [ChrAlpha/hexo-theme-cards#32]
纯文字或者只加图片的没问题。   
可像这篇 https://loafing.cn/posts/38802.html 就不行。   

另外，[hexo-blog-encrypt](https://github.com/MikeCoder/hexo-blog-encrypt)  解密后也会导致目录失效，别的倒也无所谓，但目录还是挺重要的，希望优化一下。

**Comment by ChrAlpha** [comment]
堆砌标题是很反感的，请至少尊重下 markdown 排版规范。ToC 是使用 [Hexo 官方辅助函数](https://hexo.io/docs/helpers#toc) 生成的，理论上规范使用不会出现明显问题。

至于文章加密，建议直接关闭加密文章的目录功能。ToC 是跟随页面生成好的静态内容，无从为其单独加密并随内容正文一同解密，而直接显示 ToC 会一定程度上破坏加密。
