### ISSUE TITLE
FireFox 中暗黑模式点击事件失效

### ISSUE THREAD

**Issue by JalenChuh** [ChrAlpha/hexo-theme-cards#34]
暗黑模式除了点击切换，其他自动切换都正常

FireFox 78.0.2 (64 位)

**Comment by ChrAlpha** [comment]
点击后有报错信息吗？现在暂时不方便调试。

**Comment by JalenChuh** [comment]
测试了 你的博客、Demo 和 我的博客，都无法切换

更换点击事件的写法也没用，猜测是 `localStorage` 方面的问题

**Comment by JalenChuh** [comment]
没有报错信息

**Comment by ChrAlpha** [comment]
看看是不是 Firefox 隐私策略阻止了 LS 的读写？Firefox 隐私保护一直比较激进。

**Comment by JalenChuh** [comment]
嗯....，不太确定，我对网页单独关闭了保护，但还是失效。

不过我试了一个同样通过 LS 进行控制的博客，也一样的失效了 https://hexo.fluid-dev.com
