### ISSUE TITLE
文章图片展示上的小缺陷

### ISSUE THREAD

**Issue by chclt** [ChrAlpha/hexo-theme-cards#38]
当文章的 thumbnail 宽高不够时，会留下空白，如下图：
![1](https://user-images.githubusercontent.com/20476834/88476064-f8bdf080-cf67-11ea-8eba-3ebbd9117a1e.png)
![3](https://user-images.githubusercontent.com/20476834/88476166-f1e3ad80-cf68-11ea-8d3e-bf6d751c874e.png)
我个人在 layout.styl 中添加了如下代码：
```yaml
.post-card__header
    img 
        width 100%

.post__header
    img 
        width 100%
```
当然，位图会因此失真，不过当图像宽高只差一点点时或使用 SVG 图像时是完美的。
![2](https://user-images.githubusercontent.com/20476834/88476074-0a06fd00-cf68-11ea-94af-1a7fd00728b6.png)
![4](https://user-images.githubusercontent.com/20476834/88476168-f7d98e80-cf68-11ea-9bc1-5c69531219bd.png)

**Comment by ChrAlpha** [comment]
如果你有注意到之前的代码记录，会发现曾经就是用 width: 100% 处理 thumbnail 封面图的。

后来想想直接暴力宽度填满不太合适，其实更希望按比例裁切填充封面图。当然，暂时还没实现。

**Comment by chclt** [comment]
哈哈哈明白了，是有这么一个对使用者的期愿在。

**Comment by ChrAlpha** [comment]
「Cards」v1.0 中支持了 thumbnail 自动裁切，请尝试获取最新 master 分支。
