### ISSUE TITLE
修改配置项

### ISSUE THREAD

**Issue by Konghuaiqing** [ChrAlpha/hexo-theme-cards#4]
![image](https://user-images.githubusercontent.com/58429614/80476240-af680000-897c-11ea-8faa-d7000d52ec97.png)
 官网指出，1.4.0+已废弃这两个配置项
主题配置文件中应该取消这两个配置吧

**Comment by ChrAlpha** [comment]
在 [`7d1c6e7`](https://github.com/ChrAlpha/hexo-theme-cards/commit/7d1c6e7a02424197cfea0a89250aaf1b32d2039d) 中修复，感谢提醒。
