### ISSUE TITLE
在黑暗模式下，评论系统字体颜色显示不合理.

### ISSUE THREAD

**Issue by Mulsd** [ChrAlpha/hexo-theme-cards#40]
上图，这是在[ChrAlpha 的幻想乡](https://blog.ichr.me/)里截出来的.
![图](https://cdn.jsdelivr.net/gh/Mulsd/img-bed@latest/2020/08/09/71281e05ef3bf8986d217d99530f25ef.png)
这是否是评论系统的问题？如果换用其他评论系统，能不能避免这个情况？

**Comment by ChrAlpha** [comment]
目前仅 Disqus 支持自适应亮暗色，其他第三方评论系统需要手动添加暗色的样式。
