### ISSUE TITLE
请问该主题支持本地搜索么

### ISSUE THREAD

**Issue by achenger** [ChrAlpha/hexo-theme-cards#41]
即博客内部搜索

**Comment by ChrAlpha** [comment]
主题并不内置站内搜索，但可借助插件实现。

**Comment by achenger** [comment]
是的我安装了hexo-generator-searchdb，但并不清楚如何配置到网页上，望高人指点。

**Comment by ChrAlpha** [comment]
在「Cards」v1.0 中支内置了站内搜索功能，请根据 [主题文档](https://theme-cards.ichr.me/expand/#%E7%AB%99%E5%86%85%E6%90%9C%E7%B4%A2) 进行相关配置。
