### ISSUE TITLE
Add canonical link support

### ISSUE THREAD

**Issue by haukeng** [ChrAlpha/hexo-theme-cards#44]
add canonical for SEO

[Consolidate duplicate URLs - Search Console Help](https://support.google.com/webmasters/answer/139066?hl=en)

**Comment by ChrAlpha** [comment]
Do you mean adding canonical link support for search page? I can't really realize what else ordinary pages need that.

**Comment by haukeng** [comment]
I mean adding canonical link for ordinary page like post page. It can improve page crawling efficiency according to [Google guide](https://support.google.com/webmasters/answer/139066?hl=en)

**Comment by ChrAlpha** [comment]
In the docs, Google recommends adding cannonical link when the same page can be accessed from multiple URLs. But generally, ordinary pages like post pages have a single unique link (permalink, for example `https://example.com/2020/08/19/hello-world/`). The same post page can only be accessed from this single unique link. So, adding a canonical link specifically feels a bit redundant, doesn't it?

The situation on the search page is different. There are dynamic URLs search parameters (`?s=keywords`). Thus, I think we just need to add canonical link for search page.

**Comment by ChrAlpha** [comment]
Anyway, if you still believe we should add canonical link for every ordinary page, you can modify the theme source `layout/partial/head/`.

```ejs
<link rel="canonical" href="<%= page.permalink %>" />
```

**Comment by haukeng** [comment]
> Anyway, if you still believe we should add canonical link for every ordinary page, you can modify the theme source `layout/partial/head/`.
> 
> 
> 
> ```ejs
> 
> <link rel="canonical" href="<%= page.permalink %>" />
> 
> ```

Thank you. Now can close this issue.
