### ISSUE TITLE
楼主的博客上导航栏与现有主题的发行版本不同

### ISSUE THREAD

**Issue by achenger** [ChrAlpha/hexo-theme-cards#46]
你好，楼主的[博客](https://blog.ichr.me/)上导航栏（实白色）与现有主题的发行版本（1.0.0）不同。请问是自定义的，还是该版本还未发布。
为此，建议在主题的footer上可以显示发行版本号，或在构建完毕后在其他地方体现博客主题版本。

**Comment by ChrAlpha** [comment]
一部分样式是自定义的，而且不打算将此修改合并至主题中。

至于显示版本号的建议已经加入考虑了，感谢建议！
