### ISSUE TITLE
1.0.1版主题文章标题不居中

### ISSUE THREAD

**Issue by forliuyifei** [ChrAlpha/hexo-theme-cards#47]
靠左偏移。

退回1.0.0就没问题了。

**Comment by ChrAlpha** [comment]
此问题应在 [`4b8e09`](https://github.com/ChrAlpha/hexo-theme-cards/commit/4b8e0973ebb9a35f9ecfd2442e6aa3538bed3b17) 便修复了的。

请尝试获取最新 master 分支而非下载 `1.0.1` release。
