### ISSUE TITLE
目前主题没有代码高亮

### ISSUE THREAD

**Issue by Konghuaiqing** [ChrAlpha/hexo-theme-cards#5]
望开启一款代码高亮主题，有条件可以有多个高亮主题选择
谢谢啦~

**Comment by ChrAlpha** [comment]
主题确认是开启代码高亮的了，效果可以参照 [Demo](https://theme-cards.ichr.me/demo/2019/07/code-highlight/)。

你需要在站点配置文件中开启 `highlight` 。

更多高亮选择（例如 Google Code Prettify）已有更新计划，尽情期待。
