### ISSUE TITLE
建议文章页上滑过程中“目录”按钮自动收起

### ISSUE THREAD

**Issue by forliuyifei** [ChrAlpha/hexo-theme-cards#50]
下拉的时候再显示目录按钮和回顶按钮。  
这样对手机党更友好些，截图时不被遮挡。

**Comment by ChrAlpha** [comment]
时刻监听活动事件较耗费性能，该功能再考虑一下。

**Comment by forliuyifei** [comment]
> 时刻监听活动事件较耗费性能，该功能再考虑一下。

值得考量🤦🏻‍♂️干脆默认新建 post 时 toc 为 false，有必要开目录的文章其实不多。
