### ISSUE TITLE
导航栏内文字不居中

### ISSUE THREAD

**Issue by hayschan** [ChrAlpha/hexo-theme-cards#52]
![image](https://user-images.githubusercontent.com/25737801/96288830-a1836580-1016-11eb-9dfc-68c8f3da6312.png)
![image](https://user-images.githubusercontent.com/25737801/96288926-c2e45180-1016-11eb-8611-5096480835f8.png)

如图，hover后的阴影能看出文字不在阴影中间。
测试环境：macOS 10.15.7 下的 Safari 14.0 和 Chrome 85.0

**Comment by forliuyifei** [comment]
修改 `~\themes\cards\source\css\style\_functions\header.styl`
```
    .header__left
    
        .logo__text
            font-size 18px
            padding 16px 10px 16px 10px
            border-radius 5px
```
自行调整这一项 `16px 10px 16px 10px` （分别对应上右下左填充间距）
