### ISSUE TITLE
希望增加Artalk评论系统

### ISSUE THREAD

**Issue by ltsj** [ChrAlpha/hexo-theme-cards#56]
项目地址:https://github.com/qwqcode/Artalk
~几个理由~
1.第三方的服务总觉得不太靠谱 (不太想用valine的原因
2.这样数据可以掌握在自己手里
emm 大概就是上面两点了吧

**Comment by ChrAlpha** [comment]
很好的建议，已加入计划！

**Comment by ltsj** [comment]
嘿嘿 感谢作者´͈ ᵕ `͈

**Comment by ChrAlpha** [comment]
已在 `canary` 分支尝试支持，请跟进最新版本以测试。具体实现细节可参考 [`5fde437`](https://github.com/ChrAlpha/hexo-theme-cards/commit/5fde437bcc08cfe02ad9d0c416a87f98a62e349f)。

可以继续通过此 issue 反馈有关问题。
