### ISSUE TITLE
长按首页文章链接能否显示标题文字而不是“Link” ？

### ISSUE THREAD

**Issue by forliuyifei** [ChrAlpha/hexo-theme-cards#58]
如题。
![Screenshot_20201020-133834073](https://user-images.githubusercontent.com/53306807/96545038-408bb400-12da-11eb-8d4c-535bb241d91f.jpg)
![Screenshot_20201020-134135823](https://user-images.githubusercontent.com/53306807/96545056-441f3b00-12da-11eb-8286-9a9327780453.jpg)

**Comment by ChrAlpha** [comment]
这里的链接不是链在标题上的，使得整个 Cards 块内都能点击进入文章页，而不单单只能点击标题。

> 能否显示标题文字

能。

**Comment by forliuyifei** [comment]
> 这里的链接不是链在标题上的，使得整个 Cards 块内都能点击进入文章页，而不单单只能点击标题。
> 
> > 能否显示标题文字
> 
> 能。

明白了, 归档页的文章链接果然有对应的标题 description
