### ISSUE TITLE
便签 和 折叠 插件嵌套时, 折叠失效

### ISSUE THREAD

**Issue by forliuyifei** [ChrAlpha/hexo-theme-cards#61]
```
{% note caution %}
{% fold %}

{% endfold %}
{% endnote %}
```
![image](https://user-images.githubusercontent.com/53306807/96847800-31e20000-1486-11eb-9900-9f07803078fb.png)

希望能修复一下。

反向嵌套倒是只有个样式问题。

暂时只能这样用
![image](https://user-images.githubusercontent.com/53306807/96848382-f3007a00-1486-11eb-8d00-3adfae4a70ce.png)

**Comment by ChrAlpha** [comment]
已在 `canary` 分支尝试修复，请获取最新 `canary` 分支再测试

**Comment by forliuyifei** [comment]
> 已在 `canary` 分支尝试修复，请获取最新 `canary` 分支再测试

![Screenshot_20201110-194235879](https://user-images.githubusercontent.com/53306807/98670123-2d29b100-238d-11eb-98c8-2f1e1c616a4d.jpg)

功能好了，样式有点尴尬😅
