### ISSUE TITLE
功能添加

### ISSUE THREAD

**Issue by MapleNe** [ChrAlpha/hexo-theme-cards#62]
能添加一个修改超链颜色的配置吗？

**Comment by ChrAlpha** [comment]
指的是文章中的链接，还是页面中的导航链接？

前者的话直接修改样式文件中的 `a` 即可。

**Comment by MapleNe** [comment]
> 指的是文章中的链接，还是页面中的导航链接？
> 
> 前者的话直接修改样式文件中的 `a` 即可。

main文件吗？
