### ISSUE TITLE
Adding additional languages of hljs

### ISSUE THREAD

**Issue by hayschan** [ChrAlpha/hexo-theme-cards#64]
我看hljs的[教程](https://github.com/highlightjs/highlight.js) 可以通过加一行一个语言作为额外的css，在这个主题下这应该怎么操作？
```js
<link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/highlight.min.js"></script>
<!-- and it's easy to individually load additional languages -->
<script charset="UTF-8"
 src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/languages/go.min.js"></script>
```

**Comment by ChrAlpha** [comment]
按照我的理解，Hexo 内置的 highlight.js 使用 Server-Side Rendering，无需额外引入 JS 处理。而你给出的代码样例（似乎正是 highlight.js README 中的例子）也只是增加 Go 语言的 JS 渲染组件，没有「添加额外 CSS」。

当然，如果选择使用 Client-Side Rendering，这意味着你将**关闭 Hexo 内置 highlight.js**（因为该版本经过修改仅支持服务端渲染模式）。无可避免的，你需要自行修改源码，跟着官方文档操作即可，因为这**与主题无关**。
