### ISSUE TITLE
无关紧要的小问题：更换默认的markdown渲染器之后自动摘要功能失效

### ISSUE THREAD

**Issue by forliuyifei** [ChrAlpha/hexo-theme-cards#65]
现在用的 hexo-renderer-markdown-it
似乎是这个原因导致的。
不过还是手动用 `<!--more-->` 的效果最好
现在干脆在 `/scaffolds/post.md` 的正文空一行再写上 `<!--more-->` ，很方便。

**Comment by hayschan** [comment]
谢谢提醒，一直都是每次开新文就写上 `<!--more-->`，在 scaffold 上加上更方便😂
