### ISSUE TITLE
优化建议：减少不必要的 highlight css 文件生成

### ISSUE THREAD

**Issue by forliuyifei** [ChrAlpha/hexo-theme-cards#67]
我们实际用到的高亮样式不会太多，也就 cards.yml 里面指定的几条。  
但我发现这个主题每次 hexo g 的时候都会把 `/themes/cards/source/css/highlight/` 下面所有的 css 文件放进 public 文件夹，这对生成速度有一些影响。
如果能只生成自定义的样式文件就好了。
（当然我也可以每次更新主题后手动删除多余的 css 文件。）

**Comment by ChrAlpha** [comment]
最好还是自己手动删除，毕竟无法控制所有用户的选择

**Comment by forliuyifei** [comment]
> 最好还是自己手动删除，毕竟无法控制所有用户的选择

似乎可以实现的，我试用过的 cactus 主题就是这样自动变化。（但它内置的字体对中文显示很不友好，所以弃用）

**Comment by ChrAlpha** [comment]
大概明白你的意思了，只是不把无需 css 拷进生成目录里去

**Comment by forliuyifei** [comment]
> 大概明白你的意思了，只是不把无需 css 拷进生成目录里去

对的.

**Comment by ChrAlpha** [comment]
在 `v1.5.0` 已尝试实现。
