### ISSUE TITLE
katex支持

### ISSUE THREAD

**Issue by DuranceX** [ChrAlpha/hexo-theme-cards#68]
希望能添加katex的支持

**Comment by ChrAlpha** [comment]
已在 `canary` 分支尝试支持 KaTeX，请跟进最新版本以测试。

使用方法与 MathJax 类似——在需要渲染公式页面的 `front-matter` 添加 `katex: true`。

需要注意的是，Hexo 默认渲染器 [`hexo-renderer-marked`](https://github.com/hexojs/hexo-renderer-marked) 处理公式内容时可能会有冲突，从而导致公式无法被正常渲染。这里可以换用别的渲染器（如 [`hexo-renderer-markdown-it`](https://github.com/hexojs/hexo-renderer-markdown-it)），参见 [这篇文章](https://blog.ichr.me/post/fix-mathjax-layout-bugs-in-hexo/)。

**Comment by DuranceX** [comment]
好的好的😁
