### ISSUE TITLE
添加社交媒体图标

### ISSUE THREAD

**Issue by hayschan** [ChrAlpha/hexo-theme-cards#69]
网站目标是简洁，不过有时候一些必要的联系方式感觉效果会更好。
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/25737801/100231573-2b9de280-2f62-11eb-8928-0a7326f3be13.png">
例如在博客名字下面添加。

**Comment by ChrAlpha** [comment]
该位置用文字的话区分度不够高，可能还是只能用图标。

然而图标就不得不引入其他图标库，关于标准还难以统一。有什么比较好的实现思路也欢迎分享。

**Comment by hayschan** [comment]
做了点资料搜查关于svg图标。

国外比较大的免费图标提供商，有 [Font Awesome](https://fontawesome.com/icons)，Theme [Next](https://theme-next.js.org/docs/theme-settings/sidebar.html#Sidebar-Blogrolls) 侧栏的社交媒体icon就是用的他，某些国内的图标是缺失的，e.g. Bilibili。

国内的话，有阿里的 [iconfont](https://www.iconfont.cn)，可以把一些常用的社交媒体icons（例如推特、微博、telegram、GitHub）放到 theme 包里，具体参考《[Hexo博客之优雅使用阿里iconfont图标](https://www.antmoe.com/posts/80c43671/)》。如果用户需要更多icons，可以按照教程添加更多。
