### ISSUE TITLE
很喜欢你的这个主题！我想借鉴这个风格，创造一个 hugo 的主题。

### ISSUE THREAD

**Issue by stranded-fish** [ChrAlpha/hexo-theme-cards#70]
很喜欢你的这个主题，但无奈使用的 Hugo 静态网站生成器，并没有这种类似的主题，同时我又不想转移至 hexo，所以我想借鉴您的这个主题的风格（主要是首页风格），创造一款 hugo 主题，同时也是作为我学习前端的一大动力与成果检验，谢谢。

**Comment by stranded-fish** [comment]
届时，若最终能实现一个完成度较高的作品，也十分愿意将你的 作品主题 一并放置 footer 让更多人的能够看到！感谢！

**Comment by ChrAlpha** [comment]
感谢！本主题基于 GPL-3.0 开源，也就是说你需要将你准备移植的主题同样基于 GPL-3.0 开源（自用无所谓），接下来就可以尽情享用啦！

如过程中有什么问题、想法也可以互相交流学习。
