### ISSUE TITLE
建议增加"About"页面

### ISSUE THREAD

**Issue by isunjn** [ChrAlpha/hexo-theme-cards#71]
建议增加很多博客都有的-about/关于我-页面

**Comment by forliuyifei** [comment]
请看文档 https://theme-cards.ichr.me/pages/ ，可以自己新建 Page 作为关于页，先把 hexo 的基础操作看明白再来问主题。

**Comment by isunjn** [comment]
> 请看文档 https://theme-cards.ichr.me/pages/ ，可以自己新建 Page 作为关于页，先把 hexo 的基础操作看明白再来问主题。

你好，我是看了文档的，我想表达的意思是单独为关于页做一个样式（而不是和文章页一样），文档中的独立页面配置是没有关于页的

**Comment by lzkids** [comment]
@isunjn 你可以试试在新建的page的文件里的md文档编辑，我理解正确的话
