### ISSUE TITLE
建议可以直接添加黑白主题的切换按扭

### ISSUE THREAD

**Issue by Qyir** [ChrAlpha/hexo-theme-cards#73]
白色主题下没有切换到暗黑主题的按钮。
若开启暗黑主题，则会有切换按钮；但进入页面后总是默认为暗黑主题，希望这里可以添加设置进入页面后的默认主题。
或者如标题所言，直接设置一个添加黑白主题切换按钮的配置项。

**Comment by ChrAlpha** [comment]
开启暗色主题后，每次进入页面有如下两种情况：

1. 之前通过按钮调整过深色/浅色模式，且浏览器未清除 LocalStorage，则优先应用调整指定的颜色模式
2. 之前未通过按钮调整过深色/浅色模式，且浏览器已清除 LocalStorage，则通过 `prefers-color-scheme` 判断颜色模式

照理来说不会出现「进入页面后总是默认为暗黑主题」这种情况的，目前 Demo 测试也符合预期。

P.S.  `prefers-color-scheme` 是 [Media Queries Level 5 草案](https://drafts.csswg.org/mediaqueries-5/) 中提出了深色模式的判断方式
