### ISSUE TITLE
打开 Lazyload 导致 RSS 阅读器图片无法出现

### ISSUE THREAD

**Issue by hayschan** [ChrAlpha/hexo-theme-cards#77]
**测试的 RSS 阅读器**：Reeder 4、NetNewsWire
**系统**：macOS BigSur 11.0.1

当关闭 lazyload，RSS 阅读器能显示图片。
```yaml
lazyload:
  enable: false
```
<img width="930" alt="image" src="https://user-images.githubusercontent.com/25737801/102021317-fe529080-3db9-11eb-8e32-be5a2d4e385a.png">

设置为 `true` 则 RSS 阅读器无法显示照片：
```yaml
lazyload:
  enable: true
```
<img width="887" alt="image" src="https://user-images.githubusercontent.com/25737801/102021416-a49e9600-3dba-11eb-9021-4f5caa9edab1.png">

即使设置了 `loadingImage`，也无法加载原本的图出来，只加载了 `Blank.gif`：
```yaml
lazyload:
  enable: true
  loadingImage: /uploads/Blank.gif
```
<img width="894" alt="image" src="https://user-images.githubusercontent.com/25737801/102021629-08758e80-3dbc-11eb-9d06-9b79507fd7df.png">

截图文章 [网址](https://haysc.tech/2020/12/12/ios-contact-icon/)
网站 RSS [Feed](https://haysc.tech/feed.xml)

**Comment by hayschan** [comment]
```yaml
lazyload:
  enable: true
  loadingImage:
```
在以上配置情况下，生成的 `<img>` 标签如下：
```html
<img src="https://static.haysc.tech/2020/11/image-20201017195512395.png?imageMogr2/format/webp" class="lazy" data-srcset="https://static.haysc.tech/2020/11/image-20201017195512395.png?imageMogr2/format/webp" srcset="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAABlBMVEXMzMyWlpYU2uzLAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNgAAAAAgAB9HFkpgAAAABJRU5ErkJggg==" alt="image-20201017195512395">
```

**Comment by hayschan** [comment]
和图床应该也没关系。测试过本地、腾讯云 COS、SMMS 都一样无法在RSS中加载。

**Comment by ChrAlpha** [comment]
符合预期， `srcset` 这个关键字 `src` 属性一样，可是优先级更高。目前较新的 RSS 阅读器均支持该关键词自然不能加载 `src` 中的原图了。
