### ISSUE TITLE
希望增加设置全局字体的选项

### ISSUE THREAD

**Issue by kurumiT3** [ChrAlpha/hexo-theme-cards#78]
更改博客字体有些小麻烦，每次更新时要做的修改稍多，因此希望能增加修改字体的选项。

**Comment by ChrAlpha** [comment]
考虑到不同设备的兼容性，配置 `font-family` 是个复杂的工作。提供配置项不见得会方便多少，还请有能力的用户自行修改源码。

**Comment by kurumiT3** [comment]
> 考虑到不同设备的兼容性，配置 `font-family` 是个复杂的工作。提供配置项不见得会方便多少，还请有能力的用户自行修改源码。

了解，谢谢回复
