### ISSUE TITLE
作者使用的hexo压缩插件是neat还是gulp呢

### ISSUE THREAD

**Issue by Konghuaiqing** [ChrAlpha/hexo-theme-cards#8]
偶然观察到，作者的blog源代码中使用了压缩
![image](https://user-images.githubusercontent.com/58429614/80853194-4543a980-8c61-11ea-98fc-b3ad689d10d6.png)
我的源代码中有一些空行
![image](https://user-images.githubusercontent.com/58429614/80853201-58567980-8c61-11ea-9bf4-43f6783fff0d.png)
在这里问一下作者用的是什么插件呢，谢谢

**Comment by ChrAlpha** [comment]
neat

https://github.com/rozbo/hexo-neat
