### ISSUE TITLE
缺少 <h1> 标记

### ISSUE THREAD

**Issue by forliuyifei** [ChrAlpha/hexo-theme-cards#80]
![image](https://user-images.githubusercontent.com/53306807/103434503-2573e380-4c3d-11eb-9f8d-0d153042e57c.png)
Bing 后台的 SEO报告高风险。（虽然不管它也没什么）

**Comment by ChrAlpha** [comment]
如果使用 avatar 代替 sitename 显示在封面，确实会让部分页面没有 <h1> 标记。

之后考虑添加个不可见的 <h1> 标记。
