### ISSUE TITLE
部署到gh-pages后，css样式全局颜色丢失，其他都没问题！

### ISSUE THREAD

**Issue by benjamin603** [ChrAlpha/hexo-theme-cards#81]
如题

**Comment by ChrAlpha** [comment]
请先测试是否为 GitHub Fastly CDN 的问题？且本主题部分特性对 IE 兼容性比较一般，建议使用最新 Chrome/Firefox 浏览器。

**Comment by benjamin603** [comment]
是使用的chrome，https://github.com/benjamin603/backuphexo这里是源文件，https://wnllb.cn/
这是hexo地址，至于那个CDN我不太懂

ChrAlpha <notifications@github.com> 于2021年1月6日周三 下午6:06写道：

**Comment by benjamin603** [comment]
是使用的chrome，https://github.com/benjamin603/backuphexo 这里是源文件。
https://wnllb.cn/  这是hexo地址，至于那个CDN我不太懂

**Comment by ChrAlpha** [comment]
> 是使用的chrome，https://github.com/benjamin603/backuphexo 这里是源文件。
> https://wnllb.cn/  这是hexo地址，至于那个CDN我不太懂

- 网址打不开
- 主题目录没推上来

先删掉主题目录 `.git` 开头的文件和文件夹，再将项目推送至 GitHub。

**Comment by benjamin603** [comment]
我试试，谢谢


________________________________
发件人: ChrAlpha <notifications@github.com>
发送时间: Thursday, January 7, 2021 12:04:05 PM
收件人: ChrAlpha/hexo-theme-cards <hexo-theme-cards@noreply.github.com>
抄送: Benjamin Jowe <benjamin.jowe@gmail.com>; Author <author@noreply.github.com>
主题: Re: [ChrAlpha/hexo-theme-cards] 部署到gh-pages后，css样式全局颜色丢失，其他都没问题！ (#81)


是使用的chrome，https://github.com/benjamin603/backuphexo 这里是源文件。
https://wnllb.cn/ 这是hexo地址，至于那个CDN我不太懂

  *   网址打不开
  *   主题目录没推上来

先删掉主题目录 .git 开头的文件和文件夹，再将项目推送至 GitHub。

―
