### ISSUE TITLE
暗色模式切换成亮色模式之后没办法保存

### ISSUE THREAD

**Issue by AlynxZhou** [ChrAlpha/hexo-theme-cards#84]
我的浏览器默认是暗色模式，打开你的博客也是暗色模式，然后我点击切换成亮色，当前页面切换成亮色，随后切换到别的页面比如友链，又变成了暗色。

建议利用 `localStorage` 存储一下用户选择的颜色模式。

**Comment by ChrAlpha** [comment]
参考 [这篇文章](https://blog.skk.moe/post/hello-darkmode-my-old-friend/) 优化的深色模式，就是通过 localStorage 存储来记忆深色模式。

目前我只有发现一种情况能复现你所描述的问题：Android 省电模式（而非深色模式）下默认深色时，会出现手动调节为浅色、切换页面重新变为深色的情况。

**Comment by AlynxZhou** [comment]
> 参考 [这篇文章](https://blog.skk.moe/post/hello-darkmode-my-old-friend/) 优化的深色模式，就是通过 localStorage 存储来记忆深色模式。
> 
> 目前我只有发现一种情况能复现你所描述的问题：Android 省电模式（而非深色模式）下默认深色时，会出现手动调节为浅色、切换页面重新变为深色的情况。

你试试 firefox，系统调成暗色模式

**Comment by AlynxZhou** [comment]
再补充一下，sukka 的博客在 firefox 上没有这个问题

**Comment by ChrAlpha** [comment]
> > 参考 [这篇文章](https://blog.skk.moe/post/hello-darkmode-my-old-friend/) 优化的深色模式，就是通过 localStorage 存储来记忆深色模式。
> > 目前我只有发现一种情况能复现你所描述的问题：Android 省电模式（而非深色模式）下默认深色时，会出现手动调节为浅色、切换页面重新变为深色的情况。
> 
> 你试试 firefox，系统调成暗色模式

注意到了，随后检查下。

平时较多的场景是默认亮色，手动切换暗色是正常保持暗色的，就没注意这个问题。感谢提醒！

**Comment by ChrAlpha** [comment]
[主题 Demo](https://theme-cards.ichr.me/demo/) 中似乎是没问题的，方便测试下？可能仅是我的博客有些地方没有处理好。

**Comment by AlynxZhou** [comment]
> [主题 Demo](https://theme-cards.ichr.me/demo/) 中似乎是没问题的，方便测试下？可能仅是我的博客有些地方没有处理好。

只有你的博客有问题，demo 没有

**Comment by ChrAlpha** [comment]
> > [主题 Demo](https://theme-cards.ichr.me/demo/) 中似乎是没问题的，方便测试下？可能仅是我的博客有些地方没有处理好。
> 
> 只有你的博客有问题，demo 没有

已查出是由于 darkmode 代码置于 CSS 链接前导致的，现已修复。该问题仅仅在我自己博客中出现（由于我调整了博客的大量代码而没有做足检测），Cards 中没有这个问题。
