### ISSUE TITLE
关于文章页响应式布局的问题

### ISSUE THREAD

**Issue by AlfredliuX** [ChrAlpha/hexo-theme-cards#86]
文章页在页面宽度在770px～1080px（大概）之间的时候布局不居中，如图
<img width="1137" alt="Screen Shot 2021-02-05 at 5 53 10 PM" src="https://user-images.githubusercontent.com/25657202/107018144-04be2100-67db-11eb-9ccc-8666e29236e7.png">
<img width="1137" alt="Screen Shot 2021-02-05 at 5 53 41 PM" src="https://user-images.githubusercontent.com/25657202/107018199-169fc400-67db-11eb-9ad7-cb1c6a80c4e6.png">

**Comment by ChrAlpha** [comment]
本意是留给 ToC 展示的，然而没有判断页面是否包含 ToC，才导致了如是问题。感谢反馈！

**Comment by ChrAlpha** [comment]
已在 [`093c66e`](https://github.com/ChrAlpha/hexo-theme-cards/commit/093c66e8a39dee5c158fb63ca3d86ae0b8e5cbbd) 中尝试修复，当文章页面未开启 ToC（不论是全局关闭亦或是指定该页面关闭），就不会为 ToC 预留空位。请更新至最新 `canary` 分支以测试。
