### ISSUE TITLE
【SEO优化建议】添加语言的区域性代码以及所适用的国家/地区

### ISSUE THREAD

**Issue by forliuyifei** [ChrAlpha/hexo-theme-cards#87]
![image](https://user-images.githubusercontent.com/53306807/109254962-0ef99b00-782e-11eb-8c23-e63ee51d63d1.png)

**Comment by ChrAlpha** [comment]
主题早已支持声明 `lang`，见 [`layout/layout.ejs:2`](https://github.com/ChrAlpha/hexo-theme-cards/blob/f6e25e6e7b61787684ac8779c80ea6474fa3a959/layout/layout.ejs#L2)。你只需要在**Hexo 配置文件**（注意**不是**主题配置文件）中编辑 `language` 字段即可。

至于单独使用一个 meta 元素声明语言信息的，MDN 明确不建议这么做。

![image](https://user-images.githubusercontent.com/53332481/122038872-a51af680-ce08-11eb-876b-ec3cd62be6de.png)
