### ISSUE TITLE
目前发现一个bug，gitalk文章标题过长评论系统会出现422

### ISSUE THREAD

**Issue by ssssshql** [ChrAlpha/hexo-theme-cards#89]
已经找到解决方法，套个md5就行了，希望下次更新顺便修复一下

**Comment by ChrAlpha** [comment]
应该是 GitHub Issue 字数限制吧

**Comment by 1591682454** [comment]
> 应该是GitHub Issue字数限制吧

反正《git基础使用》这个标题就不行，感觉也不长，中文多几个字就不行了
