### ISSUE TITLE
valine表情配置推荐使用json编码代替字符串拼接

### ISSUE THREAD

**Issue by MonoLogueChi** [ChrAlpha/hexo-theme-cards#9]
发现现在valine表情配置使用的是字符串拼接，这样遇到路径中存在双引号会报错，推荐使用json编码

```ejs
emojiMaps: {
    <% for (let key in theme.comments.valine.emojiMaps) { %>
    <%- key + ': \"' + theme.comments.valine.emojiMaps[key] + '\",' %>
    <% } %>
}
```

改为

```ejs
emojiMaps: <%- JSON.stringify(theme.comments.valine.emojiMaps)%>;
```

另外，推荐将整个valine配置项json编码，这样以后valine有更新配置项的时候就不需要再修改模板了

```ejs
<% if (theme.comments.valine.enable) { %>
    <% if (theme.cdn.enable && theme.cdn.js.valine) { %>
        <%- js(theme.cdn.js.valine) %>
    <% } else { %>
        <%- js('https://cdn.jsdelivr.net/npm/valine@latest/dist/Valine.min.js') %>
    <% } %>
    <script>
        var valineConifg = <%- JSON.stringify(theme.comments.valine)%>;
        valineConifg.el = '#valine_container';
        new Valine(valineConifg);
    </script>
<% } %>
```

**Comment by ChrAlpha** [comment]
感谢提醒，之前写的代码确实许多地方不尽人意。

**Comment by ChrAlpha** [comment]
在 [`b41c8f7`](https://github.com/ChrAlpha/hexo-theme-cards/commit/b41c8f707979c4cd485799040530ac5885bc2585) 中做了相关修改，由于主题配置文件中 Valine 相关配置不与官方配置项完全一致（例如 meta 与 requiredFields 处使用字符串分段而非元组存储），所以不能全部格式化，但是 emojiMaps 处确实很可行。

再次感谢！

**Comment by MonoLogueChi** [comment]
> 在 [`b41c8f7`](https://github.com/ChrAlpha/hexo-theme-cards/commit/b41c8f707979c4cd485799040530ac5885bc2585) 中做了相关修改，由于主题配置文件中 Valine 相关配置不与官方配置项完全一致（例如 meta 与 requiredFields 处使用字符串分段而非元组存储），所以不能全部格式化，但是 emojiMaps 处确实很可行。
> 
> 再次感谢！

可以全部格式化，只是要再config.yml中写成数组的形式

```yaml
meta: [nick, mail, link]
or
meta: 
  -nick
  -mail
  -link
```

**Comment by ChrAlpha** [comment]
只是感觉用数组有点不够直观（当然可能是我想多了），不过这确实是一个很好的建议，后续再看看吧。
