### ISSUE TITLE
不知道是不是bug手机浏览器点击展开导航栏后再点击无法收回

### ISSUE THREAD

**Issue by lzkids** [ChrAlpha/hexo-theme-cards#90]
用的火狐浏览器手机端

**Comment by ChrAlpha** [comment]
点击导航栏展开后，再次点击其他位置收回，而非再次点击导航栏按钮收回

**Comment by lzkids** [comment]
> 点击导航栏展开后，再次点击其他位置收回，而非再次点击导航栏按钮收回

为啥不是再点一次收回，呢样不是更舒服些吗？😂

**Comment by ChrAlpha** [comment]
> 为啥不是再点一次收回，呢样不是更舒服些吗？😂

不想引入额外 JavaScript 代码，目前这个方案是纯 CSS 实现的（`:focus`），再点一次收回不太好实现。
