### ISSUE TITLE
添加 mermaid 支持

### ISSUE THREAD

**Issue by hayschan** [ChrAlpha/hexo-theme-cards#97]
好像要在 footer 添加内容，[参考](https://wangxiaoyu-go.github.io/2018/11/23/hexo-filter-mermaid-diagrams/)：
> 

```javascript
{% if theme.mermaid.enable %}
  <script src='https://unpkg.com/mermaid@{{ theme.mermaid.version }}/dist/mermaid.min.js'></script>
  <script>
    if (window.mermaid) {
      mermaid.initialize({{ JSON.stringify(theme.mermaid.options) }});
    }
  </script>
{% endif %}
```

**Comment by ChrAlpha** [comment]
已在 [`878ee0e`](https://github.com/ChrAlpha/hexo-theme-cards/commit/878ee0e635a842a85d1606b361baddde06307692) 中尝试添加支持。

由于我没有使用 Mermaid Disgrams 的经历，故这次更新没有本地测试，还请切换至 `canary` 分支获取最新版本以测试。
